### ISSUE TITLE
Port tockloader to rust

### ISSUE THREAD

**Issue by alexandruradovici** [UPB-CS-OpenSourceUpstream/tockloader-rs#6]
This issue tracks the porting of tockloader to rust. So far tockloader is written in Python, having a lot of issues when installing it.

- [x] UPB-CS-OpenSourceUpstream/tockloader#2
- [x] UPB-CS-OpenSourceUpstream/tockloader#3
- [ ] UPB-CS-OpenSourceUpstream/tockloader-rs#5
- [ ] UPB-CS-OpenSourceUpstream/tockloader-rs#4
- [ ] UPB-CS-OpenSourceUpstream/tockloader-rs#3
- [ ] UPB-CS-OpenSourceUpstream/tockloader-rs#2
- [ ] UPB-CS-OpenSourceUpstream/tockloader-rs#1

**Comment by Ioan-Cristian** [comment]
Hello!

How can one who is not a 1st year student start working on issues number 6 and 7? At first glance, it seems that first issues such as "Set up the rust folder" are required to be able to solve issues 6 and 7. However, only 1st year students can contribute to these issues as their labels state.

Thank you in advance for your help!

**Comment by alexandruradovici** [comment]
You can start working on UPB-CS-OpenSourceUpstream/tockloader-rs#3 and UPB-CS-OpenSourceUpstream/tockloader-rs#2 and just submit the libraries in a folder.
